### PR TITLE
Added Holly's updated words lists

### PR DESCRIPTION
**Pull request by zackeller**
## What does this implement/fix? Explain your changes.
Added updated words lists from holly.

## Does this reference any currently open issues?
Yes, bad words discrepancy 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have linted my code and I have run tests locally that pass
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

## Any other comments?
…

### CODE REVIEW

**Comment by LandonPatmore** [comment]
```
aa
aah
aahed
aahing
aargh
aarrgh
aarrghh
```

These aren't bad words?

**Comment by zackeller** [comment]
@hreitmei

**Comment by hreitmei** [comment]
I was told to also remove any words that I didn't think added to the dictionary of the game. So I started doing that for the words beginning with "a" but then after that just decided to remove the bad words because there were already so many that needed to be removed. I can add those words back in if you'd like, it wouldn't be a big deal!

**Comment by sha224** [comment]
It's not a good idea to manually alter the dictionary. If you think that the dictionary has too many uncommon words, please replace it by a standard dictionary from online or I can lookup one later.

**Comment by LandonPatmore** [comment]
@hreitmei Nick @nsicilia actually found a nice dictionary of words we can use if you'd like him to give you the link?

**Comment by LandonPatmore** [comment]
@sha224 @nsicilia Found a dictionary we can use

**Comment by hreitmei** [comment]
Sounds good, whatever you guys think is best!

**Comment by sha224** [comment]
Also with the bad words, I said earlier that bad words can be valid words. Valid words are words found in the dictionary. So, first check if a word is valid and then check if it is not bad instead of just checking whether it's valid. Valid dictionary wasn't supposed to be a whitelist, It's supposed to be the dictionary.

**Comment by hreitmei** [comment]
That's what I did with the previous list given to me..

**Comment by nsicilia** [comment]
Here is a link to some google words, there in sections of 10k, 
https://github.com/first20hours/google-10000-english

**Comment by sha224** [comment]
This looks like a great collection of word lists.

**Comment by LandonPatmore** [comment]
@sha224 Can I ask why bad words cannot be put only in the bad word's list? Honest question, because I cannot see the difference if they are both in the valid and bad words list, or just in the bad words list.  The backend doesn't care that its valid, if its a bad word, it throws the play out and then will send an update to your GameDB with a bad word attempting to be played .

**Pull request closed without merging**
