### PR TITLE
Add the Dictionary Database

### PR DESCRIPTION
**Pull request by sha224**

### CODE REVIEW

**Comment by landonp1203** [comment]
Can you document this code? @sha224

**Comment by sha224** [comment]
Sí, luego.

**Comment by sha224** [comment]
com.shakhar is my reverse domain name since I own shakhar.com. Is there a particular organization domain name we will be using for this project? Then, I can use that instead.

**Comment by landonp1203** [comment]
@sha224 use something along the lines of `com.csc480.redteam` maybe?

**Comment by sha224** [comment]
That looks good.

**Comment by landonp1203** [comment]
@sha224 Could you put the docs in JavaDoc format? Sorry I didn't say before.  I want to make that standard for all Java code if you're okay with that.

**Comment by BrendanOswego** [comment]
Any update on the status of this PR? @sha224

**Comment by landonp1203** [comment]
References #18

**Pull request closed without merging**
