### PR TITLE
Fix the game board shrinking problem when placing tiles; Expand 1-step undo feature to every tile

### PR DESCRIPTION
**Pull request by henghaopu**
## What does this implement/fix? Explain your changes.
Fix the game board shrinking problem when placing tiles; Expand 1-step undo feature to every tile

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have linted my code and I have run tests locally that pass
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by BrendanOswego** [comment]
Not sure if this is just on my screen but letter are pushed up past the top portion of the tile when placed
letters-up

**Comment by BrendanOswego** [comment]
There are conflicts with this branch please fix before I can rebase and merge.

**Comment by henghaopu** [comment]
I fixed the conflict in the link "Merge branch 'dev' into dev". But I don't know what should I do next. @landonp1203 can you teach me how to do it when you are available? I would really appreciate it.

screen shot 2018-03-19 at 12 01 02 am

**Comment by landonp1203** [comment]
@henghaopu I fixed the problems.

You need to sync your local copy with the upstream so that you can update your fork accordingly as your fork is out of sync because of the changes I had to make. Please make sure you are on the dev branch before you do any of this. Run the following commands to update your local copy:

```
git fetch upstream
git reset --hard upstream/dev
git push -f origin dev
```

**Pull request merged**
