### PR TITLE
specification tests for GameDB and Dictionary applications

### PR DESCRIPTION
**Pull request by BrendanOswego**
## What does this implement/fix? Explain your changes.
Adds specification tests for the GameDB and Dictionary applications.

## Does this reference any currently open issues?
none

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have linted my code and I have run tests locally that pass
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

## Any other comments?
Used "New feature" because nothing else seems more relevant.

### CODE REVIEW

**Comment by BrendanOswego** [comment]
Travis CI failing, runs fine on local, will debug to see what's the problem

**Comment by BrendanOswego** [comment]
Teams are not getting instantiated, will fix this.

**Comment by BrendanOswego** [comment]
Should be good to go now.

**Comment by landonp1203** [comment]
@BrendanOswego Someone else on QA should probably accept this as this is QA business now.

**Comment by BrendanOswego** [comment]
@landonp1203 okay, I requested Dor to look into it.

**Comment by BrendanOswego** [comment]
Will fix conflicts once I am on Linux partition.

**Pull request merged**
