### PR TITLE
Display isTurn in dataUpdate event, Provide gameEvent textBox

### PR DESCRIPTION
**Pull request by henghaopu**
## What does this implement/fix? Explain your changes.
…

## Does this reference any currently open issues?
…

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have linted my code and I have run tests locally that pass
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

## Any other comments?
…

### CODE REVIEW

**Comment by henghaopu** [comment]
screenshot:
screen shot 2018-04-07 at 9 03 21 pm

**Comment by rzsupra17** [comment]
Could this be a problem with the hover attribute in the styling?

**Comment by henghaopu** [comment]
It's so weird. It might be the button default setting of Safari. But my Safari seems to work well. https://1drv.ms/v/s!Arsd9nV6NDIxgQVfOZZYNSPmXGoO

**Comment by henghaopu** [comment]
rzsupra17  Yeah, It might be. Since I didn't restyle hover or click attributes, browsers will decide them for us.

**Pull request merged**
