### PR TITLE
Fixed the missing tile bug which happens after a player places an inv…

### PR DESCRIPTION
**Pull request by henghaopu**
…alid word

## What does this implement/fix? Explain your changes.
…

## Does this reference any currently open issues?
…

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have linted my code and I have run tests locally that pass
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

## Any other comments?
…

### CODE REVIEW

**Comment by LandonPatmore** [comment]
Fixing now.

**Comment by LandonPatmore** [comment]
@henghaopu There seems to be a bug now that when you place letters down, and then play again, clicking on the board moves the last tile placed on the board to your mouse position, and the only way to fix it is to refresh the page

**Comment by henghaopu** [comment]
@landonp1203 I can't push the revised code easily. Can you help me add two lines of missing code to solve this problem? Just put 
    this.currentRoundtileIdsOnBoard = []
    this.selectedTileId = ''
in the grey function in the frontend_board_model.js like below: 

var grey = function() {
    // change color of tiles on board
    for (var i = 0; i < this.currentRoundtileIdsOnBoard.length; i++) {
        var tile = document.getElementById(this.currentRoundtileIdsOnBoard[i])
        tile.children[0].setAttribute('fill', 'rgb(212,212,212)') 
        tile.children[1].setAttribute('fill', '#000000')
        tile.children[2].setAttribute('fill', '#000000')
   }
    this.currentRoundtileIdsOnBoard = []
    this.selectedTileId = ''
}

**Comment by LandonPatmore** [comment]
@henghaopu yep will do

**Comment by LandonPatmore** [comment]
@henghaopu I am still having the issue, letters are still getting randomly placed after they were already played. I added your fix as well.

**Comment by henghaopu** [comment]
@landonp1203 Weird. After adding these two lines of code, the game works well. I can't change the tile position anymore after placing them.
screen shot 2018-04-17 at 12 06 52 am

**Comment by LandonPatmore** [comment]
@henghaopu Let me look to see if I can reproduce the bug again.

**Pull request merged**
